version: '3.9'

services:
  db:
    image: postgres:15
    container_name: spending-monitor-db
    restart: always
    environment:
      POSTGRES_DB: spending_monitor
      POSTGRES_USER: sm
      POSTGRES_PASSWORD: sm
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sm -d spending_monitor"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: spending-monitor-be
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spending_monitor
      SPRING_DATASOURCE_USERNAME: sm
      SPRING_DATASOURCE_PASSWORD: sm
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  db_data: