spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spending_monitor
    username: sm
    password: sm
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/spending_monitor
    username: sm
    password: sm
jwt:
  issuer: spending-monitor
  secret: change-this-super-long-random-secret-at-least-64chars____________________________________
  ttl-minutes: 120
